<fieldset class="fieldset create account">
    <legend class="legend">
        <span>
            <?php /* @escapeNotVerified */
            echo __('Additional Information') ?>
        </span>
    </legend>

<p>
<div class="field regulation required">
    <label for="regulation" class="label">
        <span>
            <?php /* @escapeNotVerified */
            echo __('Nickname') ?>
        </span>
    </label>
    <div class="control">
        <input type="text"  name="nickname" id="nickname" title="<?php /* @escapeNotVerified */
        echo __('Nickname') ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
</p>
</fieldset>